# Generated by Django 4.2.8 on 2023-12-19 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wine",
            name="slug",
        ),
    ]
