# Generated by Django 4.2.8 on 2023-12-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_alter_wine_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
