# Generated by Django 4.2.8 on 2023-12-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_alter_wine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
