# Generated by Django 4.2.8 on 2023-12-16 12:28

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0004_alter_wine_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="wines/",
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="posted_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="type_of_wine",
            field=models.CharField(
                choices=[
                    ("cabernet sauvignon", "Cabernet Sauvignon"),
                    ("pinot grigio", "Pinot Grigio"),
                    ("malbec", "Malbec"),
                    ("sauvignon blanc", "Sauvignon blanc"),
                    ("merlot", "Merlot"),
                    ("pinot noir", "Pinot noir"),
                    ("chardonnay", "Chardonnay"),
                ],
                default="Cabernet Sauvignon",
                max_length=50,
            ),
        ),
    ]
